server:
  port: 0
spring:
  application:
    name: email-service
  datasource:
    url: jdbc:mysql://localhost:3306/cims_customer?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none


  mail:
    host: smtp.gmail.com
    port: 25
    username: @@@@@@@
    password: @@@@@@@

    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          starttls:
            enable: true


